# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '4f7bce21-fdee-44b0-8eb3-665badd9a18f'
  imageRepository: 'containerapp1'
  containerRegistry: 'aksconregistery.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    ## Publish Artifacts pipeline code in addition to Build and Push 
    - bash: echo Contents in System Default Working Directory; ls -lrth $(System.DefaultWorkingDirectory)
    - bash: echo Before copying Contents in Build Artifact Directory; ls -lrth $(Build.ArtifactStagingDirectory)
     ## copying the files
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'System.DefaultWorkingDirectory/**'
        Contents: '**'
        TargetFolder: 'Build.ArtifactStagingDirectory'
        OverWrite: true
    - bash: echo After copying to Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory) 
    ## publish artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'kube-manifests'
        publishLocation: 'Container'